### ISSUE TITLE
Captions are nonsensical, is it my fault?

### ISSUE THREAD

**Issue by Delirya** [ratwithacompiler/OBS-captions-plugin#119]
Hello! I tried using this plugin for a week, and I had high hopes, but it didnt work well. I dont know if I did something wrong, or if it just hates my accent/speech, but it would put up the most jumbled nonsense for captions. It actually detected perfectly, but then I guess it gets sent out to be poked at by data hamsters.. and then it would change into a complete trainwreck. I could see that it was accurate in it's capture, but it's almost like it was being auto corrected.

I desperately would love to have this work. Using a plugin makes so much sense, and my regulars were looking forward to being able to use CC.

Is there something that I missed to make it work better?

**Comment by ratwithacompiler** [comment]
Do you maybe have the integrated OBS captions enabled too?  That are under `Tools -> Captions (Experimental)`. 

Those use the Windows built in speech recognition and are terrible, so if those were also enabled in addition to my plugin that would probably behave that way, show correctly in the captions dock preview but then have a garbled mess sent out because both the plugin and the OBS ones are sending captions.

**Comment by Delirya** [comment]
nope, tried them once and turned it off. they were.. a trainwreck lol. My accent is kiwi/british with a lil american thrown in.. but i dont think its as bad as what it looked like. I'll double check though, and try your plugin again (its such a cool plugin!).

**Comment by Delirya** [comment]
the OBS one was off, but I deselected the mic and reinstalled your plugin. had much better results! thank you
