### ISSUE TITLE
Transcript Output .txt File Location

### ISSUE THREAD

**Issue by lostchocolatelab** [ratwithacompiler/OBS-captions-plugin#13]
Thanks for the addition of this feature, the Preview window and ability to Select/ Copy is pretty great.

I haven't been able to find any of the transcript outputs...is there a default folder set for the .txt files that are output?

I see this in code: "obs_data_set_default_string(load_data, "transcript_folder_path"...but not in the Caption Settings? 

Thanks for the further guidance!

**Comment by ratwithacompiler** [comment]
Hi, yeah sorry the transcripts aren't in a release yet, unfortunately that got kinda delayed because I rewrote the config logic and wanted to test that more first before a new release, then added open captions support via text source and wanted to test that a bit more before a new release etc... and here we are 😓

There's a beta version that some people are testing currently, I'll attach that if you do wanna try it (should be stable I hope), otherwise a new main release should be available within a week or so (assuming the testing goes well).

[Closed_Captions_Plugin__Release_MacOS_HTTP 012.zip](https://github.com/ratwithacompiler/OBS-captions-plugin/files/4113098/Closed_Captions_Plugin__Release_MacOS_HTTP.012.zip)
[Closed_Captions_Plugin__v0.0.12_Windows.zip](https://github.com/ratwithacompiler/OBS-captions-plugin/files/4113099/Closed_Captions_Plugin__v0.0.12_Windows.zip)

**Comment by ratwithacompiler** [comment]
Ohh also transcript file format is very simple timestamped plaintext currently, I do wanna add SRT caption file support later but that turned out to be a bit more complicated than initially expected.
