### ISSUE TITLE
Feature Request: Multiple Caption Streams?

### ISSUE THREAD

**Issue by megaRammy** [ratwithacompiler/OBS-captions-plugin#17]
How feasible would this be? Would be extremely useful for when streaming with guests, to be able to have 2 seperate caption streams potentially, using two different sources (mic and Discord output, for instance)

**Comment by ratwithacompiler** [comment]
I considered that at the start but the problem is CEA captions are limited to only 4 lines of 32 characters (and using 4 lines can have issues with Twitch's player too and generally 3 is recommended) which makes it really hard to fit more than one person, especially since you'd also need to add some name/identifier for who's saying what as well talking up extra space too. Code wise most of it is also currently written assuming only a single caption stream so I don't think that's really feasible via my plugin, sorry.
