### ISSUE TITLE
can we add indonesian language?

### ISSUE THREAD

**Issue by adamramadhan** [ratwithacompiler/OBS-captions-plugin#19]
indonesian language?

**Comment by adamramadhan** [comment]
https://github.com/ratwithacompiler/OBS-captions-plugin/blob/5303e26e3f3c780d8d04ba7117961a00359a3079/src/caption_stream_helper.cpp found it here

**Comment by to** [comment]
I want to use Japanese language too!
I wish you uncomment that part :-)
and... i appreciate your good work.

**Comment by ratwithacompiler** [comment]
The way that Twitch/OBS native captions work only allows western character sets unfortunately (as far as I know) so that's not really possible with this plugin unfortunately.

You could use the Stream Closed Captioner extension instead, I think that may support Japanese or Indonesian https://www.twitch.tv/ext/h1ekceo16erc49snp0sine3k9ccbh9
