### ISSUE TITLE
Plugin does not generate output on Mac OS at all.

### ISSUE THREAD

**Issue by adamlogan** [ratwithacompiler/OBS-captions-plugin#21]
At current, this plugin does not generate a timed text file at all as it does for Windows. As for GDI output, I understand the GDI text frame is not available on the Mac version of OBS yet (not your fault) but still frustrating for me as a user.

I understand that it is burning the text into the stream which is not ideal, but I would totally use that if/when there is ever a working virtual camera plugin working on the Mac too. I would love a way to display the text without burning, but I imagine that would be difficult. 

I can see the captioning module working in OBS 25.08 in the preview box, but am seeing no output anywhere else. I checked in the locally recorded stream (opened with mkvtoolnix, no subtitle file in there either, I also checked the livestream on the dashboard of each respective streaming service, this plugin is a lame duck (WIP) at this point on the Mac, my preferred OS. I tested FB Livestream, Twitch, and YouTube with same results. No output anywhere other than preview window in caption plugin.

**Comment by ratwithacompiler** [comment]
Hi, sorry I haven't had time to work on this project for a while.

Regarding text source output for Open Captions, that already worked in OBS 24 (on Mac too) but apparently as I just found out OBS 25 renamed the text source id's so that was generally broken in OBS 25 both on Win and Mac, that's fixed now and should work again.

For embedded captions in local recordings that should kinda work too on Mac but OBS only supports that for some file formats (ts, mp4, mov) and there're barely any players that can actually play those back correctly with captions. MPV does correctly with .ts files but not even with .mp4 and .mov (checking with ccextractor both .mp4 and .mov do have the caption stream embedded still). Almost nothing else plays the recordings with captions at all so yeah not really useful currently.

Regarding the transcript text files, those should work on Mac I think and did for me when testing. But yeah they definitely aren't very useful in general right now as just .txt files. I do plan for .srt support at some point in the future to make local recording much more useable as playback and editing support is much better for srt but that turned out to be a bit more annoying than expected at first.

This was mostly developed for Twitch and I haven't had time to test it with YT or FB yet but it should definitely work for Twitch (with x264 at least). For streaming and recording previously multiple people did have issues with captions not working when streaming using hardware encoders but with x264 it should work on Mac too and does for me (captions not working with some hardware encoders is a general OBS issue).

**Comment by adamlogan** [comment]
Thanks for your work on this. I saw it was working recently on Twitch. I'm more likely to stream to FB or YouTube than Twitch, good to know though. Keep up the good work.
