### ISSUE TITLE
Russian language please?

### ISSUE THREAD

**Issue by sneakyjoeru** [ratwithacompiler/OBS-captions-plugin#23]
There seems to be no Russian language available. Can this be added please?

**Comment by ratwithacompiler** [comment]
The way that Twitch/OBS native captions work only allows western character sets unfortunately (as far as I know) so that's not really possible with this plugin unfortunately.

You could use the Stream Closed Captioner extension instead, I think that may support Russian but I'm not sure https://www.twitch.tv/ext/h1ekceo16erc49snp0sine3k9ccbh9
