### ISSUE TITLE
CC Settings - Text Align & Uppercase

### ISSUE THREAD

**Issue by jmytch** [ratwithacompiler/OBS-captions-plugin#30]
Is it possible to get text align in justify? Where it lines up the captions with the same width, here an example; https://www.w3schools.com/cssref/playit.asp?filename=playcss_text-align&preval=justify

I'm pretty sure it is possible to get that feature added, it would look alot more neater.

Also is it possible to have all text in uppercase as well? That would be great to have as well, and would belong in Effects > Style section.

**Comment by ratwithacompiler** [comment]
Text justify is not possible from my side. So the way CEA captions work in OBS is that they basically just embed the caption text into the stream and then the video player itself is fully responsible for displaying them however it sees fit. So to get more options in the `Closed Captions Options` section in Twitch's player you would have to ask Twitch themselves to add that to their player, neither my plugin nor OBS has any control about what settings they provide there. I do know some people have reached out to them about adding some more caption options to the player and to make the caption box freely moveable via mouse too but I'm not sure on what the status on that is or if that's actually happening.

For all uppercase text yes that would be possible to do on my side in the plugin since I can just have a setting to send text as all uppercase and that is on my todo list to add.

**Comment by ratwithacompiler** [comment]
New beta version is out now that includes option for all lowercase and all uppercase.

**Comment by jmytch** [comment]
Where do I find the uppercase in the CC options on viewer's end that stream uses your CC?

**Comment by ratwithacompiler** [comment]
That specific plugin setting is streamer side but if you want the same viewer side you can get mostly the same with using`Small Capitals` in  `Closed Caption Settings -> Text -> Font`
