### ISSUE TITLE
Any help is appreciated

### ISSUE THREAD

**Issue by jmytch** [ratwithacompiler/OBS-captions-plugin#33]
goxlr outputs mic/game/alerts from 1 cable into the streaming pc, the mic is not seprate from that at all, its one cable for everything

Settings for more unusual audio setups that don't use a mic only source in OBS (like 2 PC + audio mixer setups) is abit confusing on how to do it

**Comment by ratwithacompiler** [comment]
If the only audio the Streaming PC gets is the fully mixed audio then that's not really easily possible with my plugin without workarounds. The instructions on the bottom for 2PC setups are only for when the streaming PC still has access to only the mic itself even if that isn't used in OBS.

I went into more details about a possible workaround that some people use here https://github.com/ratwithacompiler/OBS-captions-plugin/issues/12#issuecomment-573247267 or a possible alternative via a Twitch Extension, but otherwise if OBS never has access to only the mic there isn't much it can do.
