### ISSUE TITLE
Place more Caption sources

### ISSUE THREAD

**Issue by fabiohcnobre** [ratwithacompiler/OBS-captions-plugin#34]
Today there is only one source of Caption.
I would like you to place two or more Caption sources.
For example, I use one to put a video and one for the microphone.

**Comment by Unkn0wnCat** [comment]
Building on that I think it would be nice to have 2 audio sources subtitled and seperated in the subtitles so one could have something like the following:
```
How was your day?
> My day was great, how about yours?
> Mine was also great.
Let's play something.
```
Where Lines 1, 3 and 4 would be Person / Source 1 and Line 2 would be Person / Source 2. Perhaps even different colors if Twitch supports that?

**Comment by fabiohcnobre** [comment]
That's a good idea.
That was what I needed.
You are very good.
How about a new version with this functionality?
Thank you

**Comment by ratwithacompiler** [comment]
I considered that as a feature at the start but the problem is CEA captions are limited to only 4 lines of 32 characters max (and using 4 lines can have issues with Twitch's player too and generally 3 is recommended) which makes it really hard to fit more than one person (+ an identifier for who said what). 

Also code wise most of it is currently written assuming only a single caption stream as well so I don't think that's really feasible for my plugin in the short to medium term. Would make more sense for caption extensions which have way more control about the presentation.

**Comment by fabiohcnobre** [comment]
I get it. I'm using it in my lives on Twitch and it's working really well. However, it is only subtitling my mic speech. I would like you to subtitle another audio. Or subtitle the audio of the entire live not just the mic because I do live with friends.
Thank you, good job.
