### ISSUE TITLE
Web - Show streamers

### ISSUE THREAD

**Issue by jmytch** [ratwithacompiler/OBS-captions-plugin#35]
We should have a web version that shows who is using ratwithacompiler CC, something like this https://stream-cc.gooseman.codes/showcase

It would be beneficial to people for those who wants to raid, and or follow the channel that has CC on their streams

**Comment by fabiohcnobre** [comment]
I totally disagree. The intention is to put CC in OBS Studio and not have a web version.

**Comment by jmytch** [comment]
Huh? You're not getting what I'm saying. This has nothing to do with the closed captions itself. I'm requesting if the developers could show WHO is using the closed captions on the website to list these streamers because how are you going to know which streamers have CC? Tell me it's easy to find on twitch when no streamers is using closed captions tags?

The CC plugin is staying for OBS. This is not changing at all. Have you even looked at the link I provided? It shows those streamers who used the CC extension.

**Comment by fabiohcnobre** [comment]
I understand your concern but this is more of Twitch. And not the application itself.
I went to the Streamer Showcase website and checked all the streams that are registered, none of them are doing the CC as an official twitch.

![print](https://lh4.googleusercontent.com/1YpFCY4pg8FmM6IV3ui-A99ncc76ycUCkZlf9LzjhTKxQ_iY7j6VJxB8AylMKElKh4Nudf6hzFAOgz7sLh7t=w2940-h5226-rw)

**Comment by ratwithacompiler** [comment]
That's not really easily possible because currently my plugin has no idea who's actually using it, unlike a Twitch extension that can just see a list of all it's users.

I think OBS does have optional Twitch login integration so I think I might be able to pull the channel info from that if OBS allows that and have a way in settings for people to opt into being featured on such a site (I wouldn't want that on by default as not everyone using it might want to be listed there) but honestly I don't really think that's worth overall. 

Twitch already has an official Closed Captions tag for people to be able to easily find streams with captions that includes any type of captions not just mine which seems way more useful in general too me https://www.twitch.tv/directory/all/tags/8a01ea18-df97-4046-9cff-a9a822bb96e5 

How many viewers would ever really browse a 3rd party site like that and what would be the point compared to using the Twitch directory with the captions tag to find captioned streams.

**Comment by jmytch** [comment]
Yeah sadly some streamers forget to use the Closed Captions tag before they stream and there is no way to know if they are using your CC plugin.

Hopefully OBS allows it. Thanks anyway
