### ISSUE TITLE
Linux Build

### ISSUE THREAD

**Issue by ioangogo** [ratwithacompiler/OBS-captions-plugin#5]
Noticed there isn't a Linux build

I might be able to have a look at how to build it by hand and possibly work out how to automate it with the asure pipeline your using

**Comment by ratwithacompiler** [comment]
No linux builds currently because OBS itself doesn't build successfully with caption support enabled as far as I know. Both for me locally and when trying it with their official CI setup so I don't think it's just me. Some compiler error, I've been meaning to look into that but haven't gotten around to it yet.

Linux builds should be no problem once that works.

**Comment by ratwithacompiler** [comment]
Saw your OBS Pr and added a 64bit linux CI build now. Appears to be kinda working, in my VM at least.

I'll add it to the Releases once the next OBS release with the merged fix comes out (and once master branch is actually stable again 😅), no point until then I think, but the current version is in the CI artifacts.

Thanks for the fix!

**Comment by grimmy** [comment]
You mention it's in the CI build artifacts... Is that accessible so I can  test it?

**Comment by ratwithacompiler** [comment]
you can find the CI builds for every commit in [commits section](https://github.com/ratwithacompiler/OBS-captions-plugin/commits/master) via the green checkmarks -> Detail -> View more details on Azure Pipelines -> Artifacts -> download the Linux64 one

So the current latest build would be here https://dev.azure.com/ratwithacompiler/OBS-captions-plugin/_build/results?buildId=263&view=logs&jobId=c275f7fe-e659-5231-3649-94d1ac43e3f4

But that only works in a OBS linux build with the captions fixes applied since that hasn't been merged into OBS yet, fixes here: https://github.com/ioangogo/obs-studio/commits/LinuxCaptionFix

So you would have to build that OBS version locally yourself. 
I do have a compiled OBS version with that as well that can be found here: https://dev.azure.com/ratwithacompiler/OBS_plugin_deps/_build/results?buildId=246&view=results but that takes some tinkering to get to work locally I think.

So currently it's a bit annoying until that fix is in main OBS.

**Comment by ratwithacompiler** [comment]
Ohh you came from the OBS Pr thread lol, nevermind then 😂

**Comment by grimmy** [comment]
Hehe, yep.  I've been obs from git as I've been working on some patches there, so no big deal for me :)

**Comment by grimmy** [comment]
Awesome, found it and it seems to be working just fine.  I'll be streaming in about an hour so that'll be the real test :joy:

**Comment by grimmy** [comment]
Worked great on my stream tonight, was hoping it would make it to the vod too, but doesn't look like twitch supports that.  Either way, thanks a lot! :)

**Comment by ratwithacompiler** [comment]
It does support VODs generally but I made a bunch of changes recently so current master branch had a really dumb bug, fixed now 😅

**Comment by grimmy** [comment]
Cool i'll build and try it out on my next stream

**Comment by aral** [comment]
Hey folks, any word on a Linux release? Happy to help get one together if need be :)

**Comment by ioangogo** [comment]
I think the build change is in stable now? so it should work on a stable build

**Comment by ratwithacompiler** [comment]
Yeah it should work in stable now, there's a linux beta build in releases now for testing https://github.com/ratwithacompiler/OBS-captions-plugin/releases/tag/v0.0.12b
