### ISSUE TITLE
possible to change place ?

### ISSUE THREAD

**Issue by Niko78** [ratwithacompiler/OBS-captions-plugin#52]
hi,
In using your plugin, transcription is located on top of video
is there a way to change that to put it where I want ? 
I tried in enabling a text output source in settings but it bypasses CC... so it's always displayed.
thanks
NIko

**Comment by ratwithacompiler** [comment]
Hi. That's currently not possible. OBS only supports basic CEA 608 caption text output and none of the CEA 708 positioning functionality, as far as I know.

This plugin is mostly made (and used) for Twitch which lets users set the position themselves (on PC at least) in the player settings locally so that hasn't been that much of an issue so far.

Doing it streamer side for players that support 708 isn't possibly currently without adding 708 support to OBS which isn't really doable for me.
