### ISSUE TITLE
I want more language

### ISSUE THREAD

**Issue by tsuyo5hi** [ratwithacompiler/OBS-captions-plugin#7]
I'm from Japan. I speak Japanese mostly, and wants to have closed caption on stream as own language.

**Comment by ratwithacompiler** [comment]
The way that Twitch/OBS native captions work only allows western character sets unfortunately (as far as I know) so that's not really possible with this plugin unfortunately.

You could use the Stream Closed Captioner extension instead, I think that supports Japanese: https://www.twitch.tv/ext/h1ekceo16erc49snp0sine3k9ccbh9
