### ISSUE TITLE
Hello, thanka alot for a plugin!

### ISSUE THREAD

**Issue by lcatlas** [ratwithacompiler/OBS-captions-plugin#9]
Thanks alot for a plugin, was thinking about doing it a bit later, but now it already done :)

Is it possible to add new language by coding myself? Really needed for a violin girl who streams overseas.

Thanks alot in advice for an answer.

Tested for near 3 hours for local recording - no issue. Just wanted to say thanks.

Also want to try to add translations there )

**Comment by ratwithacompiler** [comment]
It depends on the language, Google Speech-To-Text supports many languages https://cloud.google.com/speech-to-text/docs/languages however because of the way that Twitch/OBS native captions work only western character sets are possible unfortunately (as far as I know). 

So the plugin should already support all languages that are currently possible via Google STT and OBS caption output, unless I forgot to enable some that also have western char sets.

If you want languages with non western character sets you could use the Stream Closed Captioner extension instead, which uses a Twitch Overlay Extension and should work with non western character sets (I would assume, haven't tested that myself): https://www.twitch.tv/ext/h1ekceo16erc49snp0sine3k9ccbh9
